name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup Node.js (テスト用)
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    # Install dependencies and run tests
    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test --if-present

    - name: Run linting
      run: npm run lint --if-present

    # Deploy to Azure Container Apps
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy with Container Apps Up
      run: |
        az containerapp up \
          --name ${{ secrets.AZURE_CONTAINER_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --location japaneast \
          --environment trigger-game-env \
          --registry-server ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }} \
          --registry-username ${{ secrets.AZURE_REGISTRY_USERNAME }} \
          --registry-password ${{ secrets.AZURE_REGISTRY_PASSWORD }} \
          --ingress external \
          --target-port 3000 \
          --env-vars \
            NODE_ENV=production \
            PORT=3000 \
            VITE_WS_SERVER_URL="${{ vars.VITE_WS_SERVER_URL }}" \
            VITE_WEB_PUBSUB_AUTH_API_URL="${{ vars.VITE_WEB_PUBSUB_AUTH_API_URL }}" \
            WEB_PUBSUB_CONNECTION_STRING="${{ secrets.WEB_PUBSUB_CONNECTION_STRING }}"

    # Get deployment URL
    - name: Get Container App URL
      run: |
        FQDN=$(az containerapp show \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --name ${{ secrets.AZURE_CONTAINER_NAME }} \
          --query properties.configuration.ingress.fqdn \
          --output tsv)
        echo "🚀 Deployment successful!"
        echo "🌐 Application URL: https://$FQDN"